name: Deploy to cPouta

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout koodi
        uses: actions/checkout@v4

      - name: Kopioi tiedostot palvelimelle (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "index.html,funny_kitten.jpg"
          target: "/var/www/html/"
          strip_components: 0