name: Deploy to cPouta

on:
  push:
    branches:
      - main  # Suorittaa automaation aina, kun main-haara päivittyy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout koodi
        uses: actions/checkout@v4

      - name: Kopioi tiedostot palvelimelle (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "index.html"  # Mitkä tiedostot kopioidaan
          target: "/var/www/html/" # Minne ne laitetaan
          strip_components: 0